# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_real_power_df": "01-data-processing.ipynb",
         "load_real_power_dataset": "01-data-processing.ipynb",
         "load_datetime_df": "01-data-processing.ipynb",
         "load_weather_df": "01-data-processing.ipynb",
         "construct_baseline_features_target_dfs": "01-data-processing.ipynb",
         "dt_rng_to_SPs": "03a-feature-generation.ipynb",
         "create_temporal_features": "03a-feature-generation.ipynb",
         "create_dir_speed_features": "03a-feature-generation.ipynb",
         "add_col_suffix": "03a-feature-generation.ipynb",
         "isfloat": "03a-feature-generation.ipynb",
         "iterate_feature_gen_over_site_gridpoints": "03a-feature-generation.ipynb",
         "get_grid_points": "03a-feature-generation.ipynb",
         "calc_hcdh_factor": "03a-feature-generation.ipynb",
         "create_hcdh_features": "03a-feature-generation.ipynb",
         "create_feature_stats": "03a-feature-generation.ipynb",
         "create_combined_feature_stats": "03a-feature-generation.ipynb",
         "create_demand_stat_features": "03a-feature-generation.ipynb",
         "create_solar_features": "03a-feature-generation.ipynb",
         "create_prev_month_stats_df": "03a-feature-generation.ipynb",
         "create_lagged_df": "03a-feature-generation.ipynb",
         "creat_demand_ts_pcs": "03a-feature-generation.ipynb",
         "create_rate_of_change_features": "03a-feature-generation.ipynb",
         "clean_and_normalise_data": "03a-feature-generation.ipynb",
         "process_features": "03a-feature-generation.ipynb",
         "create_additional_features": "03a-feature-generation.ipynb",
         "ScikitModel": "04-model-suite.ipynb",
         "create_train_test_indexes": "04-model-suite.ipynb",
         "calculate_error_metrics": "04-model-suite.ipynb",
         "calc_month_error_metrics": "04-model-suite.ipynb",
         "construct_prediction_df": "04-model-suite.ipynb",
         "ModelSuite": "04-model-suite.ipynb",
         "load_module_attr": "04-model-suite.ipynb",
         "run_parameterised_model": "04-model-suite.ipynb",
         "plot_obsv_v_pred": "04-model-suite.ipynb",
         "create_residual_bin_avgs_s": "04-model-suite.ipynb",
         "plot_residual_bin_avgs": "04-model-suite.ipynb",
         "plot_pred_sample": "04-model-suite.ipynb",
         "flatten_list": "04-model-suite.ipynb",
         "plot_residuals_dist": "04-model-suite.ipynb",
         "visualise_errors": "04-model-suite.ipynb",
         "save_params": "04-model-suite.ipynb",
         "load_params": "04-model-suite.ipynb",
         "test_parameterised_model": "08-testing.ipynb"}

modules = ["data.py",
           "feature.py",
           "suite.py",
           "models.py",
           "test.py"]

doc_url = "https://AyrtonB.github.io/WPD-Hackathon/"

git_url = "https://github.com/AyrtonB/WPD-Hackathon"

def custom_doc_links(name): return None
