# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08-testing.ipynb (unless otherwise specified).

__all__ = ['test_parameterised_model']

# Cell
import os
import pytest

from wpdhack import suite

# Cell
def test_parameterised_model(params_fp: str='data/params/test.yml'):
    params = suite.load_params(params_fp)
    model_suite, error_metrics, df_pred, input_data = suite.run_parameterised_model(**params)

    assert error_metrics['skill_score'] < 0.55

    return