# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_real_power_df": "01-data-processing.ipynb",
         "load_real_power_dataset": "01-data-processing.ipynb",
         "load_weather_df": "01-data-processing.ipynb",
         "df_to_gdf": "02-spatial-analysis.ipynb",
         "load_subsation_locs_gdf": "02-spatial-analysis.ipynb",
         "load_weather_grid_locs_gdf": "02-spatial-analysis.ipynb"}

modules = ["data.py",
           "spatial.py"]

doc_url = "https://AyrtonB.github.io/WPD-Hackathon/"

git_url = "https://github.com/AyrtonB/WPD-Hackathon"

def custom_doc_links(name): return None
