# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_real_power_df": "01-data-processing.ipynb",
         "load_real_power_dataset": "01-data-processing.ipynb",
         "load_weather_df": "01-data-processing.ipynb",
         "construct_baseline_features_target_dfs": "01-data-processing.ipynb",
         "df_to_gdf": "02-spatial-analysis.ipynb",
         "load_subsation_locs_gdf": "02-spatial-analysis.ipynb",
         "load_weather_grid_locs_gdf": "02-spatial-analysis.ipynb",
         "dt_rng_to_SPs": "03a-feature-generation.ipynb",
         "create_temporal_features": "03a-feature-generation.ipynb",
         "create_dir_speed_features": "03a-feature-generation.ipynb",
         "calc_hcdh_factor": "03a-feature-generation.ipynb",
         "create_hcdh_features": "03a-feature-generation.ipynb",
         "create_prev_month_stats_df": "03a-feature-generation.ipynb",
         "create_lagged_df": "03a-feature-generation.ipynb",
         "create_additional_features": "03a-feature-generation.ipynb",
         "process_features": "03a-feature-generation.ipynb",
         "ScikitModel": "04-model-suite.ipynb",
         "create_train_test_indexes": "04-model-suite.ipynb",
         "calculate_error_metrics": "04-model-suite.ipynb",
         "ModelSuite": "04-model-suite.ipynb",
         "load_module_attr": "04-model-suite.ipynb",
         "run_parameterised_model": "04-model-suite.ipynb",
         "save_params": "04-model-suite.ipynb",
         "load_params": "04-model-suite.ipynb"}

modules = ["data.py",
           "spatial.py",
           "feature.py",
           "suite.py"]

doc_url = "https://AyrtonB.github.io/WPD-Hackathon/"

git_url = "https://github.com/AyrtonB/WPD-Hackathon"

def custom_doc_links(name): return None
